---
# Configuration of the Cycloid stack
version: '2'
name: 'Node.js App from GitLab'
canonical: 'node-app-gitlab'
description: This stack deploys a Node.js app built by Gitlab CI in a single instance.
author: 'Olivier de Turckheim'
image: 'https://nodejs.org/static/images/logo.png'
status: 'private'
keywords:
- node
- redis
- demo
- provider:aws
- provider:azure
- provider:gcp
technologies:
- technology: node
  version: "14.17.6"

config:
  gitlab-ci:
    name: 'gitlab-ci'
    description: 'Deploys a Node.js app from GitLab CI in a single AWS instance'
    cloud_provider: aws
    # Pipeline and variable configuration for the AWS CD pipeline use case
    pipeline:
      pipeline:
        path: 'pipeline/gitlab-ci/pipeline.yml'
      variables:
        path: 'pipeline/gitlab-ci/variables.sample.yml'
        destination: '($ project $)/pipeline/gitlab-ci/($ environment $)/variables.yml'
    # Configuration of ansible for provisionning
    ansible:
      main:
        path: 'ansible/gitlab-ci/environments/node.yml.sample'
        destination: '($ project $)/ansible/gitlab-ci/environments/($ environment $)-node.yml'
    # Configuration of terraform (leave .sample extension to prevent terraform executing the sample file)
    terraform:
      main:
        path: 'terraform/main.tf.sample'
        destination: '($ project $)/terraform/($ environment $)/main.tf'