---
gitlab-ci:
  pipeline:
    Cloud Provider:
      - name: "AWS access key"
        description: "Amazon AWS access key for Terraform."
        key: aws_access_key
        widget: cy_cred
        type: string
        default: "((aws_cycloid-demo.access_key))"
        required: true
      - name: "AWS secret key"
        description: "Amazon AWS secret key for Terraform."
        key: aws_secret_key
        widget: cy_cred
        type: string
        default: "((aws_cycloid-demo.secret_key))"
        required: true
      - name: "Amazon AWS region"
        description: "Amazon AWS region to use for Terraform."
        key: aws_region
        widget: auto_complete
        type: string
        values: ["eu-north-1","ap-south-1","eu-west-3","eu-west-2","eu-west-1","ap-northeast-2","ap-northeast-1","sa-east-1","ca-central-1","ap-southeast-1","ap-southeast-2","eu-central-1","us-east-1","us-east-2","us-west-1","us-west-2"]
        default: eu-west-1
        required: true

    Terraform remote state file:
      - name: "Terraform storage bucket"
        description: "AWS S3 bucket name to store terraform remote state file."
        key: terraform_storage_bucket_name
        widget: simple_text
        type: string
        default: ($ organization_canonical $)-terraform-remote-state
        required: true

    Keypair for new instances:
      - name: "Keypair public"
        description: "The public SSH key, for SSH access to newly-created instances."
        key: keypair_public
        widget: cy_cred
        type: string
        required: true
        default: "((custom_keypair.ssh_pub))"
        required: true
      - name: "Keypair private"
        description: "The private SSH key allowing ansible to run playbooks in the instance."
        key: keypair_private
        widget: cy_cred
        type: string
        required: true
        default: "((custom_keypair.ssh_prv))"
        required: true

    Stack Configuration:
      - name: "Config repository"
        key: git_repository
        type: string
        widget: cy_crs
        description: "Git repository URL containing the config of the stack."
        default: "git@github.com:cycloidio/cycloid-stacks-test.git"
        required: true
      - name: "Config git key"
        description: "SSH key pair to fetch the config Git repository."
        key: git_private_key
        type: string
        widget: cy_cred
        default: "((git_github.ssh_key))"
        required: true
      - name: "Config branch"
        description: "Branch of the config Git repository."
        key: git_branch
        widget: cy_branch
        type: string
        source: git_repository
        default: "config"
        required: true

  terraform:
    Node:
      - name: "VPC ID"
        description: "The ID of the VPC."
        key: vpc_id
        widget: simple_text
        type: string
        required: true
        default: "vpc-832beae8"
        required: true
      - name: "Instance type"
        description: "Instance type for the Node instance."
        key: nexus_instance_type
        widget: slider_list
        type: string
        default: "t3a.micro"
        values:
            - "t3a.nano"
            - "t3a.micro"
            - "t3a.medium"
            - "t3a.large"
            - "t3a.xlarge"
        required: true
      - name: "Disk size"
        unit: Go
        description: "Disk size for the Node instance."
        key: node_disk_size
        widget: slider_range
        type: integer
        default: 10
        values:
            - 10
            - 250
        required: true
      - name: "Port"
        description: "Port where Node app service is exposed."
        key: node_port
        widget: simple_text
        type: string
        default: "8081"
        required: true