---
- name: install Nexus Repository
  hosts: tag_role_nexus:&tag_project_{{ project }}:&tag_cycloid_io_true:&tag_env_{{ env }}
  become: yes

  vars_files:
    - "environments/default_nexus.yml"
    - ["environments/{{ env }}-nexus.yml", "environments/empty.yml"]

  vars:
    java_version: 8
    java_home: "/usr/lib/jvm/java-{{ java_version }}-openjdk-amd64"

  tasks:
  # Creating nexus user and group
  - name: Add group "nexus"
    group:
      name: nexus

  - name: Add user "nexus"  
    user:
      name: nexus
      groups: nexus

  # Increasing max number of open files on the system for the user nexus
  - name: Set file descriptor limit to 65536  
    sysctl:
      name: fs.file-max
      value: 65536
      sysctl_file: /etc/sysctl.conf
      reload: yes

  - name: Add nofile soft limit for the user nexus  
    pam_limits:
      domain: nexus
      limit_type: soft
      limit_item: nofile
      value: 65536

  - name: Add nofile hard limit for the user nexus  
    pam_limits:
      domain: nexus
      limit_type: hard
      limit_item: nofile
      value: 65536

  # Installing JAVA
  - name: Install openjdk 8
    apt:
      name: "openjdk-{{ java_version }}-jdk"
      state: present

  - name: make sure /etc/profile.d exists
    file: 
      path: /etc/profile.d
      state: directory

  - name: export JAVA_HOME and add its bin dir in the PATH
    template:
      src:  java_home.sh.j2
      dest: /etc/profile.d/java_home.sh
      mode: "a+x"

  # Installing Nexus Repository
  - name: Download and unarchive Nexus Repository installer
    unarchive:
      src: "https://download.sonatype.com/nexus/3/latest-unix.tar.gz"
      dest: "/opt"
      remote_src: yes
      owner: nexus
      group: nexus

  # - name: rename nexus directory
  #   command: mv /opt/nexus-3* /opt/nexus
  #   become: yes

  - name: create link to nexus directory
  ansible.builtin.file:
    src: /opt/nexus-3*
    dest: /opt/nexus
    owner: nexus
    group: nexus
    state: link

  - name: copy nexus.rc
    copy:
      src: nexus.rc
      dest: /opt/nexus/bin/nexus.rc
      owner: nexus
      group: nexus

 # Installing nexus as a service and enable it
  - name: copy nexus.service
    copy:
      src: nexus.service
      dest: /etc/systemd/system/nexus.service
      owner: nexus
      group: nexus

  - name: Enable a timer unit for dnf-automatic
    systemd:
      name: nexus.service
      state: started
      enabled: yes
      daemon_reload: yes