---
- name: install Nexus Repository
  hosts: tag_role_nexus:&tag_project_{{ project }}:&tag_cycloid_io_true:&tag_env_{{ env }}
  become: yes

  vars_files:
    - "environments/default_nexus.yml"
    - ["environments/{{ env }}-nexus.yml", "environments/empty.yml"]

  vars:
    java_version: 8

  roles:
  - geerlingguy.java