---
- name: install Nexus Repository
  hosts: tag_role_nexus:&tag_project_{{ project }}:&tag_cycloid_io_true:&tag_env_{{ env }}
  become: yes

  vars_files:
    - "environments/default_nexus.yml"
    - ["environments/{{ env }}-nexus.yml", "environments/empty.yml"]

  vars:
    java_version: 8


  pre_tasks:
  - name: Add group "nexus"
    group:
      name: nexus

  - name: Add user "nexus"  
    user:
      name: nexus
      groups: nexus

  - name: Set file descriptor limit to 65536  
    sysctl:
      name: fs.file-max
      value: 65536
      sysctl_file: /etc/sysctl.conf
      reload: yes

  - name: Add nofile soft limit for the user nexus  
    pam_limits:
      domain: nexus
      limit_type: soft
      limit_item: nofile
      value: 65536

  - name: Add nofile hard limit for the user nexus  
    pam_limits:
      domain: nexus
      limit_type: hard
      limit_item: nofile
      value: 65536

  - name: Install gtar (unarchive module prerequisite) 
    apt:
      name: gtar
      state: latest


  roles:
  - olivier2t.common
  - geerlingguy.java


  post_tasks:
  - name: Download and unarchive Nexus Repository installer
    src: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
    dest: /tmp