---
- name: install Nexus Repository
  hosts: tag_role_nexus:&tag_project_{{ project }}:&tag_cycloid_io_true:&tag_env_{{ env }}
  become: yes

  vars_files:
    - "environments/default_nexus.yml"
    - ["environments/{{ env }}-nexus.yml", "environments/empty.yml"]

  vars:
    java_version: 8
    java_home: "/usr/lib/jvm/java-{{ java_version }}-openjdk-amd64"


  pre_tasks:
  - name: Add group "nexus"
    group:
      name: nexus

  - name: Add user "nexus"  
    user:
      name: nexus
      groups: nexus

  - name: Set file descriptor limit to 65536  
    sysctl:
      name: fs.file-max
      value: 65536
      sysctl_file: /etc/sysctl.conf
      reload: yes

  - name: Add nofile soft limit for the user nexus  
    pam_limits:
      domain: nexus
      limit_type: soft
      limit_item: nofile
      value: 65536

  - name: Add nofile hard limit for the user nexus  
    pam_limits:
      domain: nexus
      limit_type: hard
      limit_item: nofile
      value: 65536

  - name: Install openjdk 8.
    apt:
      name: "openjdk-{{ java_version }}-jdk"
      state: present

  - name: make sure /etc/profile.d exists
    file: 
      path: /etc/profile.d
      state: directory

  - name: export JAVA_HOME and add its bin dir in the PATH
    template:
      src:  java_home.sh.j2
      dest: /etc/profile.d/java_home.sh
      mode: "a+x"


  # roles:
  # - geerlingguy.java


  post_tasks:
  - name: create /opt/nexus directory
    file:
      path: "/opt/nexus"
      state: directory
      mode: 0755

  - name: Download and unarchive Nexus Repository installer
    unarchive:
      src: "https://download.sonatype.com/nexus/3/latest-unix.tar.gz"
      dest: "/opt/nexus"
      remote_src: yes