---
- name: install Node app
  hosts: tag_role_node:&tag_project_{{ project }}:&tag_cycloid_io_true:&tag_env_{{ env }}
  become: yes

  vars_files:
  - "environments/default_node.yml"
  - ["environments/{{ env }}-node.yml", "environments/empty.yml"]


  tasks:
  # Creating node user and group
  - name: Add group "node"
    group:
      name: "{{ node_os_group }}"
      state: present